from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 80, 251, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 16, 16))
        self.label_3.setObjectName("label_3")
        self.cb_mode_simple = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_mode_simple.setGeometry(QtCore.QRect(120, 20, 70, 17))
        self.cb_mode_simple.setChecked(True)
        self.cb_mode_simple.setTristate(False)
        self.cb_mode_simple.setObjectName("cb_mode_simple")
        self.cb_LEDs_odd = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_LEDs_odd.setGeometry(QtCore.QRect(200, 190, 70, 17))
        self.cb_LEDs_odd.setObjectName("cb_LEDs_odd")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 31))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.cb_mode_flashing = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_mode_flashing.setGeometry(QtCore.QRect(120, 60, 81, 17))
        self.cb_mode_flashing.setObjectName("cb_mode_flashing")
        self.cb_LEDs_even = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_LEDs_even.setGeometry(QtCore.QRect(200, 170, 70, 17))
        self.cb_LEDs_even.setObjectName("cb_LEDs_even")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 240, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 290, 71, 31))
        self.label_10.setObjectName("label_10")
        self.slider_opacity = QtWidgets.QSlider(self.centralwidget)
        self.slider_opacity.setGeometry(QtCore.QRect(120, 110, 151, 22))
        self.slider_opacity.setMaximum(100)
        self.slider_opacity.setProperty("value", 100)
        self.slider_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.slider_opacity.setObjectName("slider_opacity")
        self.le_color_red = QtWidgets.QLineEdit(self.centralwidget)
        self.le_color_red.setGeometry(QtCore.QRect(200, 240, 71, 20))
        self.le_color_red.setObjectName("le_color_red")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 320, 251, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.cb_mode_cycling = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_mode_cycling.setGeometry(QtCore.QRect(120, 40, 70, 17))
        self.cb_mode_cycling.setObjectName("cb_mode_cycling")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 300, 51, 16))
        self.label_9.setObjectName("label_9")
        self.pb_apply = QtWidgets.QPushButton(self.centralwidget)
        self.pb_apply.setGeometry(QtCore.QRect(190, 370, 81, 23))
        self.pb_apply.setObjectName("pb_apply")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 270, 51, 16))
        self.label_8.setObjectName("label_8")
        self.cb_LEDs_logo = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_LEDs_logo.setGeometry(QtCore.QRect(120, 190, 70, 17))
        self.cb_LEDs_logo.setChecked(True)
        self.cb_LEDs_logo.setObjectName("cb_LEDs_logo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 71, 31))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 210, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 130, 31, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.le_color_green = QtWidgets.QLineEdit(self.centralwidget)
        self.le_color_green.setGeometry(QtCore.QRect(200, 270, 71, 20))
        self.le_color_green.setObjectName("le_color_green")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 140, 251, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.cb_LEDs_all = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_LEDs_all.setGeometry(QtCore.QRect(120, 170, 70, 17))
        self.cb_LEDs_all.setChecked(True)
        self.cb_LEDs_all.setObjectName("cb_LEDs_all")
        self.le_color_blue = QtWidgets.QLineEdit(self.centralwidget)
        self.le_color_blue.setGeometry(QtCore.QRect(200, 300, 71, 20))
        self.le_color_blue.setObjectName("le_color_blue")
        self.cb_LEDs_advanced = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_LEDs_advanced.setGeometry(QtCore.QRect(330, 20, 141, 23))
        self.cb_LEDs_advanced.setObjectName("cb_LEDs_advanced")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 50, 201, 341))
        self.label_6.setObjectName("label_6")
        self.rb_LED_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_3.setGeometry(QtCore.QRect(350, 90, 112, 23))
        self.rb_LED_3.setText("")
        self.rb_LED_3.setAutoExclusive(False)
        self.rb_LED_3.setObjectName("rb_LED_3")
        self.rb_LED_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_6.setGeometry(QtCore.QRect(340, 150, 112, 23))
        self.rb_LED_6.setText("")
        self.rb_LED_6.setAutoExclusive(False)
        self.rb_LED_6.setObjectName("rb_LED_6")
        self.rb_LED_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_8.setGeometry(QtCore.QRect(340, 190, 112, 23))
        self.rb_LED_8.setText("")
        self.rb_LED_8.setAutoExclusive(False)
        self.rb_LED_8.setObjectName("rb_LED_8")
        self.rb_LED_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_10.setGeometry(QtCore.QRect(350, 250, 112, 23))
        self.rb_LED_10.setText("")
        self.rb_LED_10.setAutoExclusive(False)
        self.rb_LED_10.setObjectName("rb_LED_10")
        self.rb_LED_12 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_12.setGeometry(QtCore.QRect(360, 300, 112, 23))
        self.rb_LED_12.setText("")
        self.rb_LED_12.setAutoExclusive(False)
        self.rb_LED_12.setObjectName("rb_LED_12")
        self.rb_LED_15 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_15.setGeometry(QtCore.QRect(410, 370, 112, 23))
        self.rb_LED_15.setText("")
        self.rb_LED_15.setAutoExclusive(False)
        self.rb_LED_15.setObjectName("rb_LED_15")
        self.rb_LED_14 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_14.setGeometry(QtCore.QRect(380, 360, 112, 23))
        self.rb_LED_14.setText("")
        self.rb_LED_14.setAutoExclusive(False)
        self.rb_LED_14.setObjectName("rb_LED_14")
        self.rb_LED_13 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_13.setGeometry(QtCore.QRect(370, 330, 112, 23))
        self.rb_LED_13.setText("")
        self.rb_LED_13.setAutoExclusive(False)
        self.rb_LED_13.setObjectName("rb_LED_13")
        self.rb_LED_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_4.setGeometry(QtCore.QRect(340, 110, 112, 23))
        self.rb_LED_4.setText("")
        self.rb_LED_4.setAutoExclusive(False)
        self.rb_LED_4.setObjectName("rb_LED_4")
        self.rb_LED_18 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_18.setGeometry(QtCore.QRect(480, 330, 112, 23))
        self.rb_LED_18.setText("")
        self.rb_LED_18.setAutoExclusive(False)
        self.rb_LED_18.setObjectName("rb_LED_18")
        self.rb_LED_17 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_17.setGeometry(QtCore.QRect(470, 360, 112, 23))
        self.rb_LED_17.setText("")
        self.rb_LED_17.setAutoExclusive(False)
        self.rb_LED_17.setObjectName("rb_LED_17")
        self.rb_LED_16 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_16.setGeometry(QtCore.QRect(440, 370, 112, 23))
        self.rb_LED_16.setText("")
        self.rb_LED_16.setAutoExclusive(False)
        self.rb_LED_16.setObjectName("rb_LED_16")
        self.rb_LED_19 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_19.setGeometry(QtCore.QRect(490, 300, 112, 23))
        self.rb_LED_19.setText("")
        self.rb_LED_19.setAutoExclusive(False)
        self.rb_LED_19.setObjectName("rb_LED_19")
        self.rb_LED_23 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_23.setEnabled(True)
        self.rb_LED_23.setGeometry(QtCore.QRect(500, 190, 112, 23))
        self.rb_LED_23.setText("")
        self.rb_LED_23.setAutoExclusive(False)
        self.rb_LED_23.setObjectName("rb_LED_23")
        self.rb_LED_25 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_25.setGeometry(QtCore.QRect(500, 150, 112, 23))
        self.rb_LED_25.setText("")
        self.rb_LED_25.setAutoExclusive(False)
        self.rb_LED_25.setObjectName("rb_LED_25")
        self.rb_LED_26 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_26.setGeometry(QtCore.QRect(500, 130, 112, 23))
        self.rb_LED_26.setText("")
        self.rb_LED_26.setAutoExclusive(False)
        self.rb_LED_26.setObjectName("rb_LED_26")
        self.rb_LED_28 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_28.setGeometry(QtCore.QRect(500, 90, 112, 23))
        self.rb_LED_28.setText("")
        self.rb_LED_28.setAutoExclusive(False)
        self.rb_LED_28.setObjectName("rb_LED_28")
        self.rb_LED_29 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_29.setGeometry(QtCore.QRect(490, 70, 112, 23))
        self.rb_LED_29.setText("")
        self.rb_LED_29.setAutoExclusive(False)
        self.rb_LED_29.setObjectName("rb_LED_29")
        self.rb_LED_31 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_31.setGeometry(QtCore.QRect(440, 60, 21, 23))
        self.rb_LED_31.setText("")
        self.rb_LED_31.setAutoExclusive(False)
        self.rb_LED_31.setObjectName("rb_LED_31")
        self.rb_LED_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_0.setGeometry(QtCore.QRect(410, 60, 21, 23))
        self.rb_LED_0.setText("")
        self.rb_LED_0.setAutoExclusive(False)
        self.rb_LED_0.setObjectName("rb_LED_0")
        self.rb_LED_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_2.setGeometry(QtCore.QRect(360, 70, 21, 23))
        self.rb_LED_2.setText("")
        self.rb_LED_2.setAutoExclusive(False)
        self.rb_LED_2.setObjectName("rb_LED_2")
        self.rb_LED_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_5.setGeometry(QtCore.QRect(340, 130, 112, 23))
        self.rb_LED_5.setText("")
        self.rb_LED_5.setAutoExclusive(False)
        self.rb_LED_5.setObjectName("rb_LED_5")
        self.rb_LED_27 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_27.setGeometry(QtCore.QRect(500, 110, 112, 23))
        self.rb_LED_27.setText("")
        self.rb_LED_27.setAutoExclusive(False)
        self.rb_LED_27.setObjectName("rb_LED_27")
        self.rb_LED_30 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_30.setGeometry(QtCore.QRect(470, 60, 21, 23))
        self.rb_LED_30.setText("")
        self.rb_LED_30.setAutoExclusive(False)
        self.rb_LED_30.setObjectName("rb_LED_30")
        self.rb_LED_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_1.setGeometry(QtCore.QRect(380, 60, 21, 23))
        self.rb_LED_1.setText("")
        self.rb_LED_1.setAutoExclusive(False)
        self.rb_LED_1.setObjectName("rb_LED_1")
        self.rb_LED_20 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_20.setGeometry(QtCore.QRect(490, 270, 112, 23))
        self.rb_LED_20.setText("")
        self.rb_LED_20.setAutoExclusive(False)
        self.rb_LED_20.setObjectName("rb_LED_20")
        self.rb_LED_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_11.setGeometry(QtCore.QRect(350, 270, 112, 23))
        self.rb_LED_11.setText("")
        self.rb_LED_11.setAutoExclusive(False)
        self.rb_LED_11.setObjectName("rb_LED_11")
        self.rb_LED_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_9.setGeometry(QtCore.QRect(340, 220, 112, 23))
        self.rb_LED_9.setText("")
        self.rb_LED_9.setAutoExclusive(False)
        self.rb_LED_9.setObjectName("rb_LED_9")
        self.rb_LED_24 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_24.setGeometry(QtCore.QRect(500, 170, 112, 23))
        self.rb_LED_24.setText("")
        self.rb_LED_24.setAutoExclusive(False)
        self.rb_LED_24.setObjectName("rb_LED_24")
        self.rb_LED_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_7.setGeometry(QtCore.QRect(340, 170, 112, 23))
        self.rb_LED_7.setText("")
        self.rb_LED_7.setAutoExclusive(False)
        self.rb_LED_7.setObjectName("rb_LED_7")
        self.rb_LED_22 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_22.setGeometry(QtCore.QRect(500, 220, 112, 23))
        self.rb_LED_22.setText("")
        self.rb_LED_22.setAutoExclusive(False)
        self.rb_LED_22.setObjectName("rb_LED_22")
        self.rb_LED_32 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_32.setGeometry(QtCore.QRect(420, 310, 112, 23))
        self.rb_LED_32.setText("")
        self.rb_LED_32.setAutoExclusive(False)
        self.rb_LED_32.setObjectName("rb_LED_32")
        self.rb_LED_21 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_LED_21.setGeometry(QtCore.QRect(490, 250, 112, 23))
        self.rb_LED_21.setText("")
        self.rb_LED_21.setAutoExclusive(False)
        self.rb_LED_21.setObjectName("rb_LED_21")
        self.label_6.raise_()
        self.line_3.raise_()
        self.label_3.raise_()
        self.cb_mode_simple.raise_()
        self.cb_LEDs_odd.raise_()
        self.label.raise_()
        self.cb_mode_flashing.raise_()
        self.cb_LEDs_even.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.slider_opacity.raise_()
        self.le_color_red.raise_()
        self.line_4.raise_()
        self.cb_mode_cycling.raise_()
        self.label_9.raise_()
        self.pb_apply.raise_()
        self.label_8.raise_()
        self.cb_LEDs_logo.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.le_color_green.raise_()
        self.line_2.raise_()
        self.cb_LEDs_all.raise_()
        self.le_color_blue.raise_()
        self.cb_LEDs_advanced.raise_()
        self.rb_LED_3.raise_()
        self.rb_LED_6.raise_()
        self.rb_LED_8.raise_()
        self.rb_LED_10.raise_()
        self.rb_LED_12.raise_()
        self.rb_LED_15.raise_()
        self.rb_LED_14.raise_()
        self.rb_LED_13.raise_()
        self.rb_LED_4.raise_()
        self.rb_LED_18.raise_()
        self.rb_LED_17.raise_()
        self.rb_LED_16.raise_()
        self.rb_LED_19.raise_()
        self.rb_LED_23.raise_()
        self.rb_LED_25.raise_()
        self.rb_LED_26.raise_()
        self.rb_LED_28.raise_()
        self.rb_LED_29.raise_()
        self.rb_LED_31.raise_()
        self.rb_LED_0.raise_()
        self.rb_LED_2.raise_()
        self.rb_LED_5.raise_()
        self.rb_LED_27.raise_()
        self.rb_LED_30.raise_()
        self.rb_LED_1.raise_()
        self.rb_LED_20.raise_()
        self.rb_LED_11.raise_()
        self.rb_LED_9.raise_()
        self.rb_LED_24.raise_()
        self.rb_LED_7.raise_()
        self.rb_LED_22.raise_()
        self.rb_LED_32.raise_()
        self.rb_LED_21.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Driver", "Driver"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.cb_mode_simple.setText(_translate("MainWindow", "Simple"))
        self.cb_LEDs_odd.setText(_translate("MainWindow", "Odd"))
        self.label.setText(_translate("MainWindow", "Mode"))
        self.cb_mode_flashing.setText(_translate("MainWindow", "Flashing"))
        self.cb_LEDs_even.setText(_translate("MainWindow", "Even"))
        self.label_7.setText(_translate("MainWindow", "Red"))
        self.label_5.setText(_translate("MainWindow", "LEDs"))
        self.label_10.setText(_translate("MainWindow", "Color"))
        self.le_color_red.setText(_translate("MainWindow", "255"))
        self.cb_mode_cycling.setText(_translate("MainWindow", "Cycling"))
        self.label_9.setText(_translate("MainWindow", "Blue"))
        self.pb_apply.setText(_translate("MainWindow", "Apply"))
        self.label_8.setText(_translate("MainWindow", "Green"))
        self.cb_LEDs_logo.setText(_translate("MainWindow", "Logo"))
        self.label_2.setText(_translate("MainWindow", "Opacity"))
        self.label_4.setText(_translate("MainWindow", "100"))
        self.le_color_green.setText(_translate("MainWindow", "255"))
        self.cb_LEDs_all.setText(_translate("MainWindow", "All"))
        self.le_color_blue.setText(_translate("MainWindow", "255"))
        self.cb_LEDs_advanced.setText(_translate("MainWindow", "Advanced LEDs"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"hpc_kingston_hyperx_pulsefire_surge_rgb-1.jpg\"/></p></body></html>"))
